from collections import namedtuple

import contextlib

from functools import cache, reduce, wraps

import inspect

from inspect import Signature, Parameter

import logging

from numbers import Number, Real

import operator

import re

import warnings



import numpy as np



import matplotlib as mpl

from . import _api, cbook

from .path import Path

from .transforms import (BboxBase, Bbox, IdentityTransform, Transform, TransformedBbox,

                         TransformedPatchPath, TransformedPath)



_log = logging.getLogger(__name__)





def _prevent_rasterization(draw):

                                                                            

                                                                            

                                                                       

                                                                            

                            



    @wraps(draw)

    def draw_wrapper(artist, renderer, *args, **kwargs):

        if renderer._raster_depth == 0 and renderer._rasterizing:

                                                              

                                                                

            renderer.stop_rasterizing()

            renderer._rasterizing = False



        return draw(artist, renderer, *args, **kwargs)



    draw_wrapper._supports_rasterization = False

    return draw_wrapper





def allow_rasterization(draw):

    



    @wraps(draw)

    def draw_wrapper(artist, renderer):

        try:

            if artist.get_rasterized():

                if renderer._raster_depth == 0 and not renderer._rasterizing:

                    renderer.start_rasterizing()

                    renderer._rasterizing = True

                renderer._raster_depth += 1

            else:

                if renderer._raster_depth == 0 and renderer._rasterizing:

                                                                      

                                                                     

                    renderer.stop_rasterizing()

                    renderer._rasterizing = False



            if artist.get_agg_filter() is not None:

                renderer.start_filter()



            return draw(artist, renderer)

        finally:

            if artist.get_agg_filter() is not None:

                renderer.stop_filter(artist.get_agg_filter())

            if artist.get_rasterized():

                renderer._raster_depth -= 1

            if (renderer._rasterizing and (fig := artist.get_figure(root=True)) and

                    fig.suppressComposite):

                                                        

                renderer.stop_rasterizing()

                renderer.start_rasterizing()



    draw_wrapper._supports_rasterization = True

    return draw_wrapper





def _finalize_rasterization(draw):

    

    @wraps(draw)

    def draw_wrapper(artist, renderer, *args, **kwargs):

        result = draw(artist, renderer, *args, **kwargs)

        if renderer._rasterizing:

            renderer.stop_rasterizing()

            renderer._rasterizing = False

        return result

    return draw_wrapper





def _stale_axes_callback(self, val):

    if self.axes:

        self.axes.stale = val





_XYPair = namedtuple("_XYPair", "x y")





class Artist:

    



    zorder = 0



    def __init_subclass__(cls):



                                                                     

                                                                             

                                                                            

                    



        if not hasattr(cls.draw, "_supports_rasterization"):

            cls.draw = _prevent_rasterization(cls.draw)



                                                                          

                                                        



        if not hasattr(cls.set, '_autogenerated_signature'):

                                                                           

                                                  

                                                                            

                                                                         

                                            

            return



        cls.set = lambda self, **kwargs: Artist.set(self, **kwargs)

        cls.set.__name__ = "set"

        cls.set.__qualname__ = f"{cls.__qualname__}.set"

        cls._update_set_signature_and_docstring()



    _PROPERTIES_EXCLUDED_FROM_SET = [

        'navigate_mode',                              

        'figure',                                                           

                                                            

        '3d_properties',                                                    

    ]



    @classmethod

    def _update_set_signature_and_docstring(cls):

        

        cls.set.__signature__ = Signature(

            [Parameter("self", Parameter.POSITIONAL_OR_KEYWORD),

             *[Parameter(prop, Parameter.KEYWORD_ONLY, default=_api.UNSET)

               for prop in ArtistInspector(cls).get_setters()

               if prop not in Artist._PROPERTIES_EXCLUDED_FROM_SET]])

        cls.set._autogenerated_signature = True



        cls.set.__doc__ = (

            "Set multiple properties at once.\n\n"

            "Supported properties are\n\n"

            + kwdoc(cls))



    def __init__(self):

        self._stale = True

        self.stale_callback = None

        self._axes = None

        self._parent_figure = None



        self._transform = None

        self._transformSet = False

        self._visible = True

        self._animated = False

        self._alpha = None

        self.clipbox = None

        self._clippath = None

        self._clipon = True

        self._label = ''

        self._picker = None

        self._rasterized = False

        self._agg_filter = None

                                                                               

                                                

        self._mouseover = type(self).get_cursor_data != Artist.get_cursor_data

        self._callbacks = cbook.CallbackRegistry(signals=["pchanged"])

        try:

            self.axes = None

        except AttributeError:

                                                                     

            pass

        self._remove_method = None

        self._url = None

        self._gid = None

        self._snap = None

        self._sketch = mpl.rcParams['path.sketch']

        self._path_effects = mpl.rcParams['path.effects']

        self._sticky_edges = _XYPair([], [])

        self._in_layout = True



    def __getstate__(self):

        d = self.__dict__.copy()

        d['stale_callback'] = None

        return d



    def remove(self):

        



                                                                             

                                                                     

                                                                          

                                                                       

        if self._remove_method is not None:

            self._remove_method(self)

                                  

            self.stale_callback = None

            _ax_flag = False

            if hasattr(self, 'axes') and self.axes:

                                                

                self.axes._mouseover_set.discard(self)

                self.axes.stale = True

                self.axes = None                                     

                _ax_flag = True



            if (fig := self.get_figure(root=False)) is not None:

                if not _ax_flag:

                    fig.stale = True

                self._parent_figure = None



        else:

            raise NotImplementedError('cannot remove artist')

                                                                        

                                                                              

                                                                              

                                                                       

                                  



    def have_units(self):

        

        ax = self.axes

        return ax and any(axis.have_units() for axis in ax._axis_map.values())



    def convert_xunits(self, x):

        

        ax = getattr(self, 'axes', None)

        if ax is None or ax.xaxis is None:

            return x

        return ax.xaxis.convert_units(x)



    def convert_yunits(self, y):

        

        ax = getattr(self, 'axes', None)

        if ax is None or ax.yaxis is None:

            return y

        return ax.yaxis.convert_units(y)



    @property

    def axes(self):

        

        return self._axes



    @axes.setter

    def axes(self, new_axes):

        if (new_axes is not None and self._axes is not None

                and new_axes != self._axes):

            raise ValueError("Can not reset the Axes. You are probably trying to reuse "

                             "an artist in more than one Axes which is not supported")

        self._axes = new_axes

        if new_axes is not None and new_axes is not self:

            self.stale_callback = _stale_axes_callback



    @property

    def stale(self):

        

        return self._stale



    @stale.setter

    def stale(self, val):

        self._stale = val



                                                                       

                                                                          

                                                                     

        if self._animated:

            return



        if val and self.stale_callback is not None:

            self.stale_callback(self, val)



    def get_window_extent(self, renderer=None):

        

        return Bbox([[0, 0], [0, 0]])



    def get_tightbbox(self, renderer=None):

        

        bbox = self.get_window_extent(renderer)

        if self.get_clip_on():

            clip_box = self.get_clip_box()

            if clip_box is not None:

                bbox = Bbox.intersection(bbox, clip_box)

            clip_path = self.get_clip_path()

            if clip_path is not None and bbox is not None:

                clip_path = clip_path.get_fully_transformed_path()

                bbox = Bbox.intersection(bbox, clip_path.get_extents())

        return bbox



    def add_callback(self, func):

        

                                                                              

                                       

        return self._callbacks.connect("pchanged", lambda: func(self))



    def remove_callback(self, oid):

        

        self._callbacks.disconnect(oid)



    def pchanged(self):

        

        self._callbacks.process("pchanged")



    def is_transform_set(self):

        

        return self._transformSet



    def set_transform(self, t):

        

        self._transform = t

        self._transformSet = True

        self.pchanged()

        self.stale = True



    def get_transform(self):

        

        if self._transform is None:

            self._transform = IdentityTransform()

        elif (not isinstance(self._transform, Transform)

              and hasattr(self._transform, '_as_mpl_transform')):

            self._transform = self._transform._as_mpl_transform(self.axes)

        return self._transform



    def get_children(self):

        

        return []



    def _different_canvas(self, event):

        

        return (getattr(event, "canvas", None) is not None

                and (fig := self.get_figure(root=True)) is not None

                and event.canvas is not fig.canvas)



    def contains(self, mouseevent):

        

        _log.warning("%r needs 'contains' method", self.__class__.__name__)

        return False, {}



    def pickable(self):

        

        return self.get_figure(root=False) is not None and self._picker is not None



    def pick(self, mouseevent):

        

        from .backend_bases import PickEvent                    

                   

        if self.pickable():

            picker = self.get_picker()

            if callable(picker):

                inside, prop = picker(self, mouseevent)

            else:

                inside, prop = self.contains(mouseevent)

            if inside:

                PickEvent("pick_event", self.get_figure(root=True).canvas,

                          mouseevent, self, **prop)._process()



                       

        for a in self.get_children():

                                                           

            ax = getattr(a, 'axes', None)

            if (isinstance(a, mpl.figure.SubFigure)

                    or mouseevent.inaxes is None or ax is None

                    or mouseevent.inaxes == ax):

                                                               

                                                                       

                                                                    

                                              

                                                                        

                                                                       

                a.pick(mouseevent)



    def set_picker(self, picker):

        

        self._picker = picker



    def get_picker(self):

        

        return self._picker



    def get_url(self):

        

        return self._url



    def set_url(self, url):

        

        self._url = url



    def get_gid(self):

        

        return self._gid



    def set_gid(self, gid):

        

        self._gid = gid



    def get_snap(self):

        

        if mpl.rcParams['path.snap']:

            return self._snap

        else:

            return False



    def set_snap(self, snap):

        

        self._snap = snap

        self.stale = True



    def get_sketch_params(self):

        

        return self._sketch



    def set_sketch_params(self, scale=None, length=None, randomness=None):

        

        if scale is None:

            self._sketch = None

        else:

            self._sketch = (scale, length or 128.0, randomness or 16.0)

        self.stale = True



    def set_path_effects(self, path_effects):

        

        self._path_effects = path_effects

        self.stale = True



    def get_path_effects(self):

        return self._path_effects



    def get_figure(self, root=False):

        

        if root and self._parent_figure is not None:

            return self._parent_figure.get_figure(root=True)



        return self._parent_figure



    def set_figure(self, fig):

        

                                        

        if self._parent_figure is fig:

            return

                                                                       

                                                                      

                                                                        

                                                                        

                               

        if self._parent_figure is not None:

            raise RuntimeError("Can not put single artist in "

                               "more than one figure")

        self._parent_figure = fig

        if self._parent_figure and self._parent_figure is not self:

            self.pchanged()

        self.stale = True



    figure = property(get_figure, set_figure,

                      doc=("The (Sub)Figure that the artist is on.  For more "

                           "control, use the `get_figure` method."))



    def set_clip_box(self, clipbox):

        

        _api.check_isinstance((BboxBase, None), clipbox=clipbox)

        if clipbox != self.clipbox:

            self.clipbox = clipbox

            self.pchanged()

            self.stale = True



    def set_clip_path(self, path, transform=None):

        

        from matplotlib.patches import Patch, Rectangle



        success = False

        if transform is None:

            if isinstance(path, Rectangle):

                self.clipbox = TransformedBbox(Bbox.unit(),

                                               path.get_transform())

                self._clippath = None

                success = True

            elif isinstance(path, Patch):

                self._clippath = TransformedPatchPath(path)

                success = True

            elif isinstance(path, tuple):

                path, transform = path



        if path is None:

            self._clippath = None

            success = True

        elif isinstance(path, Path):

            self._clippath = TransformedPath(path, transform)

            success = True

        elif isinstance(path, TransformedPatchPath):

            self._clippath = path

            success = True

        elif isinstance(path, TransformedPath):

            self._clippath = path

            success = True



        if not success:

            raise TypeError(

                "Invalid arguments to set_clip_path, of type "

                f"{type(path).__name__} and {type(transform).__name__}")

                                                                               

                                    

        self.pchanged()

        self.stale = True



    def get_alpha(self):

        

        return self._alpha



    def get_visible(self):

        

        return self._visible



    def get_animated(self):

        

        return self._animated



    def get_in_layout(self):

        

        return self._in_layout



    def _fully_clipped_to_axes(self):

        

                                                                            

                                                                          

                                                                       

                                                                         

                                                                          

        clip_box = self.get_clip_box()

        clip_path = self.get_clip_path()

        return (self.axes is not None

                and self.get_clip_on()

                and (clip_box is not None or clip_path is not None)

                and (clip_box is None

                     or np.all(clip_box.extents == self.axes.bbox.extents))

                and (clip_path is None

                     or isinstance(clip_path, TransformedPatchPath)

                     and clip_path._patch is self.axes.patch))



    def get_clip_on(self):

        

        return self._clipon



    def get_clip_box(self):

        

        return self.clipbox



    def get_clip_path(self):

        

        return self._clippath



    def get_transformed_clip_path_and_affine(self):

        

        if self._clippath is not None:

            return self._clippath.get_transformed_path_and_affine()

        return None, None



    def set_clip_on(self, b):

        

        self._clipon = b

                                                                            

                               

        self.pchanged()

        self.stale = True



    def _set_gc_clip(self, gc):

        

        if self._clipon:

            if self.clipbox is not None:

                gc.set_clip_rectangle(self.clipbox)

            gc.set_clip_path(self._clippath)

        else:

            gc.set_clip_rectangle(None)

            gc.set_clip_path(None)



    def get_rasterized(self):

        

        return self._rasterized



    def set_rasterized(self, rasterized):

        

        supports_rasterization = getattr(self.draw,

                                         "_supports_rasterization", False)

        if rasterized and not supports_rasterization:

            _api.warn_external(f"Rasterization of '{self}' will be ignored")



        self._rasterized = rasterized



    def get_agg_filter(self):

        

        return self._agg_filter



    def set_agg_filter(self, filter_func):

        

        self._agg_filter = filter_func

        self.stale = True



    def draw(self, renderer):

        

        if not self.get_visible():

            return

        self.stale = False



    def set_alpha(self, alpha):

        

        if alpha is not None and not isinstance(alpha, Real):

            raise TypeError(

                f'alpha must be numeric or None, not {type(alpha)}')

        if alpha is not None and not (0 <= alpha <= 1):

            raise ValueError(f'alpha ({alpha}) is outside 0-1 range')

        if alpha != self._alpha:

            self._alpha = alpha

            self.pchanged()

            self.stale = True



    def _set_alpha_for_array(self, alpha):

        

        if isinstance(alpha, str):

            raise TypeError("alpha must be numeric or None, not a string")

        if not np.iterable(alpha):

            Artist.set_alpha(self, alpha)

            return

        alpha = np.asarray(alpha)

        if not (0 <= alpha.min() and alpha.max() <= 1):

            raise ValueError('alpha must be between 0 and 1, inclusive, '

                             f'but min is {alpha.min()}, max is {alpha.max()}')

        self._alpha = alpha

        self.pchanged()

        self.stale = True



    def set_visible(self, b):

        

        if b != self._visible:

            self._visible = b

            self.pchanged()

            self.stale = True



    def set_animated(self, b):

        

        if self._animated != b:

            self._animated = b

            self.pchanged()



    def set_in_layout(self, in_layout):

        

        self._in_layout = in_layout



    def get_label(self):

        

        return self._label



    def set_label(self, s):

        

        label = str(s) if s is not None else None

        if label != self._label:

            self._label = label

            self.pchanged()

            self.stale = True



    def get_zorder(self):

        

        return self.zorder



    def set_zorder(self, level):

        

        if level is None:

            level = self.__class__.zorder

        if level != self.zorder:

            self.zorder = level

            self.pchanged()

            self.stale = True



    @property

    def sticky_edges(self):

        

        return self._sticky_edges



    def update_from(self, other):

        

        self._transform = other._transform

        self._transformSet = other._transformSet

        self._visible = other._visible

        self._alpha = other._alpha

        self.clipbox = other.clipbox

        self._clipon = other._clipon

        self._clippath = other._clippath

        self._label = other._label

        self._sketch = other._sketch

        self._path_effects = other._path_effects

        self.sticky_edges.x[:] = other.sticky_edges.x.copy()

        self.sticky_edges.y[:] = other.sticky_edges.y.copy()

        self.pchanged()

        self.stale = True



    def properties(self):

        

        return ArtistInspector(self).properties()



    def _update_props(self, props, errfmt):

        

        ret = []

        with cbook._setattr_cm(self, eventson=False):

            for k, v in props.items():

                                                                       

                                            

                if k == "axes":

                    ret.append(setattr(self, k, v))

                else:

                    func = getattr(self, f"set_{k}", None)

                    if not callable(func):

                        raise AttributeError(

                            errfmt.format(cls=type(self), prop_name=k),

                            name=k)

                    ret.append(func(v))

        if ret:

            self.pchanged()

            self.stale = True

        return ret



    def update(self, props):

        

        return self._update_props(

            props, "{cls.__name__!r} object has no property {prop_name!r}")



    def _internal_update(self, kwargs):

        

        return self._update_props(

            kwargs, "{cls.__name__}.set() got an unexpected keyword argument "

            "{prop_name!r}")



    def set(self, **kwargs):

                                                        

                                                                        

                 

        return self._internal_update(cbook.normalize_kwargs(kwargs, self))



    @contextlib.contextmanager

    def _cm_set(self, **kwargs):

        

        orig_vals = {k: getattr(self, f"get_{k}")() for k in kwargs}

        try:

            self.set(**kwargs)

            yield

        finally:

            self.set(**orig_vals)



    def findobj(self, match=None, include_self=True):

        

        if match is None:                      

            def matchfunc(x):

                return True

        elif isinstance(match, type) and issubclass(match, Artist):

            def matchfunc(x):

                return isinstance(x, match)

        elif callable(match):

            matchfunc = match

        else:

            raise ValueError('match must be None, a matplotlib.artist.Artist '

                             'subclass, or a callable')



        artists = reduce(operator.iadd,

                         [c.findobj(matchfunc) for c in self.get_children()], [])

        if include_self and matchfunc(self):

            artists.append(self)

        return artists



    def get_cursor_data(self, event):

        

        return None



    def format_cursor_data(self, data):

        

        if np.ndim(data) == 0 and hasattr(self, "_format_cursor_data_override"):

                                                                        

                                                                                   

                          

            return self._format_cursor_data_override(data)

        else:

            try:

                data[0]

            except (TypeError, IndexError):

                data = [data]

            data_str = ', '.join(f'{item:0.3g}' for item in data

                                 if isinstance(item, Number))

            return "[" + data_str + "]"



    def get_mouseover(self):

        

        return self._mouseover



    def set_mouseover(self, mouseover):

        

        self._mouseover = bool(mouseover)

        ax = self.axes

        if ax:

            if self._mouseover:

                ax._mouseover_set.add(self)

            else:

                ax._mouseover_set.discard(self)



    mouseover = property(get_mouseover, set_mouseover)               





def _get_tightbbox_for_layout_only(obj, *args, **kwargs):

    

    try:

        return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})

    except TypeError:

        return obj.get_tightbbox(*args, **kwargs)





class ArtistInspector:

    



    def __init__(self, o):

        

        if not isinstance(o, Artist):

            if np.iterable(o):

                o = list(o)

                if len(o):

                    o = o[0]



        self.oorig = o

        if not isinstance(o, type):

            o = type(o)

        self.o = o



        self.aliasd = self.get_aliases()



    def get_aliases(self):

        

        names = [name for name in dir(self.o)

                 if name.startswith(('set_', 'get_'))

                    and callable(getattr(self.o, name))]

        aliases = {}

        for name in names:

            func = getattr(self.o, name)

            if not self.is_alias(func):

                continue

            propname = re.search(f"`({name[:4]}.*)`",                 

                                 inspect.getdoc(func)).group(1)

            aliases.setdefault(propname[4:], set()).add(name[4:])

        return aliases



    _get_valid_values_regex = re.compile(

        r"\n\s*(?:\.\.\s+)?ACCEPTS:\s*((?:.|\n)*?)(?:$|(?:\n\n))"

    )



    def get_valid_values(self, attr):

        



        name = 'set_%s' % attr

        if not hasattr(self.o, name):

            raise AttributeError(f'{self.o} has no function {name}')

        func = getattr(self.o, name)



        if hasattr(func, '_kwarg_doc'):

            return func._kwarg_doc



        docstring = inspect.getdoc(func)

        if docstring is None:

            return 'unknown'



        if docstring.startswith('Alias for '):

            return None



        match = self._get_valid_values_regex.search(docstring)

        if match is not None:

            return re.sub("\n *", " ", match.group(1))



                                                                       

                                                                       

        param_name = func.__code__.co_varnames[1]

                                                                         

                                                                         

        match = re.search(fr"(?m)^ *\*?{param_name} : (.+)", docstring)

        if match:

            return match.group(1)



        return 'unknown'



    def _replace_path(self, source_class):

        

        replace_dict = {'_base._AxesBase': 'Axes',

                        '_axes.Axes': 'Axes'}

        for key, value in replace_dict.items():

            source_class = source_class.replace(key, value)

        return source_class



    def get_setters(self):

        

        setters = []

        for name in dir(self.o):

            if not name.startswith('set_'):

                continue

            func = getattr(self.o, name)

            if (not callable(func)

                    or self.number_of_parameters(func) < 2

                    or self.is_alias(func)):

                continue

            setters.append(name[4:])

        return setters



    @staticmethod

    @cache

    def number_of_parameters(func):

        

        return len(inspect.signature(func).parameters)



    @staticmethod

    @cache

    def is_alias(method):

        



        ds = inspect.getdoc(method)

        if ds is None:

            return False



        return ds.startswith('Alias for ')



    def aliased_name(self, s):

        

        aliases = ''.join(' or %s' % x for x in sorted(self.aliasd.get(s, [])))

        return s + aliases



    _NOT_LINKABLE = {

                                                                        

                                                                           

                                                                        

                                    

        'matplotlib.image._ImageBase.set_alpha',

        'matplotlib.image._ImageBase.set_array',

        'matplotlib.image._ImageBase.set_data',

        'matplotlib.image._ImageBase.set_filternorm',

        'matplotlib.image._ImageBase.set_filterrad',

        'matplotlib.image._ImageBase.set_interpolation',

        'matplotlib.image._ImageBase.set_interpolation_stage',

        'matplotlib.image._ImageBase.set_resample',

        'matplotlib.text._AnnotationBase.set_annotation_clip',

    }



    def aliased_name_rest(self, s, target):

        

                                                            

        if target in self._NOT_LINKABLE:

            return f'``{s}``'



        aliases = ''.join(

            f' or :meth:`{a} <{target}>`' for a in sorted(self.aliasd.get(s, [])))

        return f':meth:`{s} <{target}>`{aliases}'



    def pprint_setters(self, prop=None, leadingspace=2):

        

        if leadingspace:

            pad = ' ' * leadingspace

        else:

            pad = ''

        if prop is not None:

            accepts = self.get_valid_values(prop)

            return f'{pad}{prop}: {accepts}'



        lines = []

        for prop in sorted(self.get_setters()):

            accepts = self.get_valid_values(prop)

            name = self.aliased_name(prop)

            lines.append(f'{pad}{name}: {accepts}')

        return lines



    def pprint_setters_rest(self, prop=None, leadingspace=4):

        

        if leadingspace:

            pad = ' ' * leadingspace

        else:

            pad = ''

        if prop is not None:

            accepts = self.get_valid_values(prop)

            return f'{pad}{prop}: {accepts}'



        prop_and_qualnames = []

        for prop in sorted(self.get_setters()):

                                                                           

            for cls in self.o.__mro__:

                method = getattr(cls, f"set_{prop}", None)

                if method and method.__doc__ is not None:

                    break

            else:                           

                method = getattr(self.o, f"set_{prop}")

            prop_and_qualnames.append(

                (prop, f"{method.__module__}.{method.__qualname__}"))



        names = [self.aliased_name_rest(prop, target)

                 .replace('_base._AxesBase', 'Axes')

                 .replace('_axes.Axes', 'Axes')

                 for prop, target in prop_and_qualnames]

        accepts = [self.get_valid_values(prop)

                   for prop, _ in prop_and_qualnames]



        col0_len = max(len(n) for n in names)

        col1_len = max(len(a) for a in accepts)

        table_formatstr = pad + '   ' + '=' * col0_len + '   ' + '=' * col1_len



        return [

            '',

            pad + '.. table::',

            pad + '   :class: property-table',

            '',

            table_formatstr,

            pad + '   ' + 'Property'.ljust(col0_len)

            + '   ' + 'Description'.ljust(col1_len),

            table_formatstr,

            *[pad + '   ' + n.ljust(col0_len) + '   ' + a.ljust(col1_len)

              for n, a in zip(names, accepts)],

            table_formatstr,

            '',

        ]



    def properties(self):

        

        o = self.oorig

        getters = [name for name in dir(o)

                   if name.startswith('get_') and callable(getattr(o, name))]

        getters.sort()

        d = {}

        for name in getters:

            func = getattr(o, name)

            if self.is_alias(func):

                continue

            try:

                with warnings.catch_warnings():

                    warnings.simplefilter('ignore')

                    val = func()

            except Exception:

                continue

            else:

                d[name[4:]] = val

        return d



    def pprint_getters(self):

        

        lines = []

        for name, val in sorted(self.properties().items()):

            if getattr(val, 'shape', ()) != () and len(val) > 6:

                s = str(val[:6]) + '...'

            else:

                s = str(val)

            s = s.replace('\n', ' ')

            if len(s) > 50:

                s = s[:50] + '...'

            name = self.aliased_name(name)

            lines.append(f'    {name} = {s}')

        return lines





def getp(obj, property=None):

    

    if property is None:

        insp = ArtistInspector(obj)

        ret = insp.pprint_getters()

        print('\n'.join(ret))

        return

    return getattr(obj, 'get_' + property)()



       

get = getp





def setp(obj, *args, file=None, **kwargs):

    



    if isinstance(obj, Artist):

        objs = [obj]

    else:

        objs = list(cbook.flatten(obj))



    if not objs:

        return



    insp = ArtistInspector(objs[0])



    if not kwargs and len(args) < 2:

        if args:

            print(insp.pprint_setters(prop=args[0]), file=file)

        else:

            print('\n'.join(insp.pprint_setters()), file=file)

        return



    if len(args) % 2:

        raise ValueError('The set args must be string, value pairs')



    funcvals = dict(zip(args[::2], args[1::2]))

    ret = [o.update(funcvals) for o in objs] + [o.set(**kwargs) for o in objs]

    return list(cbook.flatten(ret))





def kwdoc(artist):

    

    ai = ArtistInspector(artist)

    return ('\n'.join(ai.pprint_setters_rest(leadingspace=4))

            if mpl.rcParams['docstring.hardcopy'] else

            'Properties:\n' + '\n'.join(ai.pprint_setters(leadingspace=4)))



                                                                           

                

Artist._update_set_signature_and_docstring()

