



from cycler import cycler



import matplotlib.pyplot as plt

import numpy as np



import matplotlib as mpl



mpl.rcParams['lines.linewidth'] = 2

mpl.rcParams['lines.linestyle'] = '--'

data = np.random.randn(50)

plt.plot(data)



    

                                                                         

                                             



mpl.rcParams['axes.prop_cycle'] = cycler(color=['r', 'g', 'b', 'y'])

plt.plot(data)                      



    

                                                                             

                                                          

                                                              



mpl.rc('lines', linewidth=4, linestyle='-.')

plt.plot(data)



    

                       

                       

 

                                                                              

                                              



with mpl.rc_context({'lines.linewidth': 2, 'lines.linestyle': ':'}):

    plt.plot(data)



    

                                                                       

                             





@mpl.rc_context({'lines.linewidth': 3, 'lines.linestyle': '-'})

def plotting_function():

    plt.plot(data)



plotting_function()



    

                                                              

                   

 

                                                                             

                                        



    

                                    

 

                    

                    

 

                                                                    

                                                                      

                                                                   

                                                                       

                                                                     

                                                                       

                                                                        

                                                               

                                                                

                                                                     

                                                                        

                                                                     

                                                     

 

                                                                       

                                                      

                                                                          

                                                                        

             



plt.style.use('ggplot')



    

                                    



print(plt.style.available)



    

                         

                         

 

                                                                        

                                     

 

                                       

                                                         

 

                        

                        

                        

                          

                         

                         

 

                                                                            

                                            

 

                                        

                                                        

 

 

                     

                     

 

                                                                              

                                                                     

                                                                            

                                                                           

                                                                 

                                              

 

                                                                       

                                                                           

                                                      

                                                                      

                                                                 

                                                                          

                                                                        

                                                                        

                                        

 

                                                                              

                                                                     

 

                                                                

                                                     

 

                                        

                                    

 

 

                  

                  

 

                                                                            

                                                                             

                                                                         

                    

 

                                        

                                                           

 

                                                                              

                                

 

 

                   

                   

 

                                                                             

                                                                            

                                                                        

                                                      



with plt.style.context('dark_background'):

    plt.plot(np.sin(np.linspace(0, 2 * np.pi)), 'r-o')

plt.show()



    

                                          

 

                               

                               

 

                                                                           

                                                                              

                                                                              

                                                                            

                                                                           

                                                                         

                                    

 

                                                                            

                                                                     

 

                                                

                                        

 

                                                                        

 

                                        

                                                  

                                                                             

                        

 

                                                                        

 

                                               

 

                                                              

                                        

                                                                  

                                                                         

                                                                      

                                                                   

                                        

 

                                                                       

                                

                                                                 

                                                                      

                                                      

                            

 

                                                                     

                                         

 

                         

                                     

                                               

 

                                                                      

                                                                         

 

                          

 

                                       

                                       

 

                                                                   

 

 

                                            

                                   

