import pytest





def test_sphinx_gallery_example_header():

    

    pytest.importorskip('sphinx_gallery', minversion='0.16.0')

    from sphinx_gallery import gen_rst



    EXAMPLE_HEADER = """
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "{0}"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        :ref:`Go to the end <sphx_glr_download_{1}>`
        to download the full example code.{2}

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_{1}:

"""

    assert gen_rst.EXAMPLE_HEADER == EXAMPLE_HEADER

