



import matplotlib.pyplot as plt



fig = plt.figure(figsize=(3, 3), linewidth=1, edgecolor='black')

fig.text(.2, .7, "plain text: alpha > beta")

fig.text(.2, .5, "Mathtext: $\\alpha > \\beta$")

fig.text(.2, .3, r"raw string Mathtext: $\alpha > \beta$")



    

              

 

                                                                                

 

                                                                              

                                                                             

                                                                             

                                                                    

 

           

                                                                               

                                                                            

              

 

 

                    

                    

 

                                                                                

                                                                               

                                                                           

                                                                           

                                                 



fig = plt.figure(figsize=(3, 3), linewidth=1, edgecolor='black')

fig.suptitle("Number of unescaped $")

fig.text(.1, .7, r"odd: $ \alpha $ = $1")

fig.text(.1, .5, r"even: $ \beta $= $ 2 $")

fig.text(.1, .3, r'odd: $ \gamma $= \$3 $')

fig.text(.1, .1, r'even: $ \delta $ = $ \$4 $')



    

                                                                             

                                                                               

                                                                        

                                

 

                                                                           

                                                                          

 

                                    

 

                                                               

 

 

                             

                             

                                                                            

 

                             

 

           

 

                        

 

                                                               

                                                 

 

                                   

 

           

 

                              

 

                                                                          

                                                                                 

                                   

 

                                

 

           

 

                           

 

                                           

                                           

                                                                   

                                                                      

                

 

                                                           

 

          

 

           

 

                                                        

 

                                       

 

                                    

 

          

 

           

 

                               

 

                                                                            

                                                                                

         

 

                                      

 

           

 

                                 

 

                                                                                

                                                               

 

                                                 

 

           

 

                                            

 

          

          

                                                                         

 

                   

 

           

 

              

 

                                                                              

                                                                              

                                 

 

                      

 

           

 

                 

 

                     

 

       

       

 

                                                         

 

                                                                                 

                                                                                

                                                                   

 

                                                                              

                

 

                                                     

 

           

 

                                                

 

                                                                          

                                                                           

           

 

                                             

 

           

 

                                        

 

                                                                            

                                                                                

                                                                            

                                                   

 

                                             

 

                                                                                 

                                                                             

                                   

 

           

 

                                          

 

                                                                             

                                                                            

                                                                            

                                                  

 

                                           

 

                                                            

                                  

                                                            

                                                     

                                                      

                                                          

                                                            

                                                            

 

                                     

                              

                   

 

                                                                             

            

 

                                                                            

                                         

                                                                            

                                                                   

                                                                            

                                                                  

                                                                  

                                                                           

                                                                     

                                                                            

 

                                                                  

                                                                         

                         

 

                             

                  

                             

 

                                                                             

 

                               

                  

                              

 

                                                                             

 

                               

                  

                     

 

                                                                             

 

                                                    

                  

                       

 

                                                                             

 

                               

                  

                           

 

                                                                             

 

                                                              

                                                                        

                                                                             

                                                                             

                                                     

 

                                                                                   

                                                                             

              

 

              

              

                                                                            

                                                                            

                                                                       

                                                                                 

                                          

 

                                                                  

                                               

                                                                  

                                                                

                                                              

                                                                     

                                                   

                                                            

                                                            

                                                         

                                                                  

 

                                                                             

                                                                             

                                                                            

                                                         

                                                                          

                                             

                                                           

                                               

 

                                                                            

                                                                   

 

         

         

                                                                                

                                        

 

                                                                  

                                       

                                                                  

                                                    

                                                  

                                                    

                                                  

                                                   

                                                    

                                                     

                                                    

                                                  

                                                    

                                                  

                                                          

                                                                  

 

                                                                             

                             

 

                                                                  

                                       

                                                                  

                                                         

                                                           

                                                                  

 

                                                                            

                                                                              

 

                                

 

           

 

                           

 

         

         

                                                                       

                                     

 

                        

 

                                                                             

                                                                           

 

                

