

                                             



import matplotlib.pyplot as plt

import numpy as np



fig = plt.figure()

fig.subplots_adjust(top=0.8)

ax1 = fig.add_subplot(211)

ax1.set_ylabel('Voltage [V]')

ax1.set_title('A sine wave')



t = np.arange(0.0, 1.0, 0.01)

s = np.sin(2*np.pi*t)

line, = ax1.plot(t, s, color='blue', lw=2)



                                         

np.random.seed(19680801)



ax2 = fig.add_axes((0.15, 0.1, 0.7, 0.3))

n, bins, patches = ax2.hist(np.random.randn(1000), 50,

                            facecolor='yellow', edgecolor='yellow')

ax2.set_xlabel('Time [s]')



plt.show()



    

                          

 

                          

                          

 

                                                            

                                                                       

                                                                       

                                                                        

                                                                       

                                                                      

                                                                    

                                                               

                                                                      

                                                                          

                                                               

                                                                  

                                                          

 

                                                                               

                         

                                                                               

                                                  

                                                                   

                                                              

                                                    

                                         

                                               

                                                                             

                   

                                                                    

                                                    

                                                          

                                

                                                          

                                                         

                                                                            

                               

                                                                               

 

                                                                    

                                                                       

                                                                      

                                                        

 

                       

                        

 

                                                                     

                                                           

 

                                

 

                                                                      

                                                 

                                                 

                                                                        

                                                                      

                                                                              

                             

 

                         

 

                                                 

                         

                    

                        

                                 

                                                   

                       

                     

                       

                      

                        

                       

                                                                              

                                              

                                                          

                                              

                                

                   

                  

                    

                  

                         

                         

               

                               

                             

                                                                               

                                                                    

                         

                     

                         

                            

                   

                                                                         

                                                       

                  

                                                                     

                      

                 

                                                                

             

                   

             

                  

 

                                                                   

                                                              

                                                                   

 

                        

 

                   

                   

 

 

                                                                   

                                                                         

                                                                   

                                                                       

                                                                 

                                                                      

                                                                     

                                                                        

                                                                     

                                                                      

                                                                       

                                                                  

 

                       

 

                  

                  

 

                                           

                                                                      

                                            

                                                           

                            

                                                                      

                                                                 

                                                  

                                                                   

                           

 

                         

 

                                  

 

                                          

 

                                                        

 

                   

                       

 

                               

                                                                      

 

                                                                     

                                                       

                                                                   

                                                                  

                                                 

                                                   

                                                                       

                                                                            

                                                                        

                                                                 

                                             

 

                         

                       

 

 

                                                                             

                                                                              

                                                                              

                                                                               

                                                                               

                                                                            

                                                   

 

                                                                             

                                                                        

                                                               



import matplotlib.lines as lines



fig = plt.figure()



l1 = lines.Line2D([0, 1], [0, 1], transform=fig.transFigure, figure=fig)

l2 = lines.Line2D([0, 1], [1, 0], transform=fig.transFigure, figure=fig)

fig.lines.extend([l1, l2])



plt.show()



    

                                                      

 

                                                                               

                              

                                                                               

                                                    

                                              

                                                     

                                               

                                                       

                                                         

                                                       

                                                    

                                              

                                                      

                                                  

                                                                               

 

                     

 

                

                

 

                                                                   

                                                                       

                                                              

                                                                

                                                  

                                                   

                                    

                                                

                                                                        

                                                                       

                                                                      

 

                            

                                             

                                 

 

                                                      

                                                                         

                                                                               

                                                                            

                                     

 

                         

 

                                             

 

                                                                     

 

                                                                        

                                                                     

                                                                  

                      

 

                         

 

                               

                                              

 

                                              

                                                                      

                                                    

 

                         

 

                                                                        

 

                          

                                                   

 

                                      

                  

 

                                                                               

                                                                               

            

 

                                                                   

                                                                            

                                                                       

                                                                       

                                         

 

                                                                            

                                                                         

                                                                              

                                

 

                         

 

                                        

 

                                   

                                                                               

 

                                            

                                

          

 

                                                                          

                                                

                         

 

                                            

                                  

 

                                                                

                

                                

                               

 

                                               

                                                

                                

                           

                              

                                      

                                        

                                    

                                

                                  

                                                           

                                       

                                          

                                                  

                                                      

                              

                                  

                                                                              

                                      

                                          

                                                                   

                                       

                                                   

                                                   

                                                           

 

                                                       

                                   

                                

                           

                              

                                      

                                        

                                    

                                

                                  

                                                           

                                       

                                          

                                                  

                                                      

                              

                                  

                                                                              

                                      

                                          

                                                                   

                                       

                                                   

                                                   

                                                           

 

                                                                 

                                    

                

 

                                                                        

                                        

                           

 

                                                         

                                   

 

                                                                             

                                    

                  

 

                                               

                                 

 

 

                                                                     

                                                                        

                                                                         

                                   

 

                                                                               

                                                                         

                                                                               

                                                                        

                                                                          

                                                                            

                                                                          

                                                                          

                                                                          

                                                                         

                                                                               

                                                                        

                                                                              

                                                                        

                                                                               

 

 

                                                                    

                                                                      

                                                                      

                                                           

                                         

                                                                   

                                                                        

                                                   

                                                                       

                                                                       

                                                                      

          

 

                                                   

 

                                                                   

 

                                                             

                               

                                                             

                                                           

                                                             

                                                               

                                                    

                                                           

                                                          

                                                         

                                                      

                                                      

                                                             

 

                                                         

 

                     

 

                 

                 

 

                                                                       

                                                                      

                                                                       

                                                                    

                                                                       

                                                                     

                                                                     

                                                               

 

                                                                               

                                                                         

                                                                               

                                                                              

                                                                              

                                                                            

                                                                          

                                                                          

                                                                          

                                                                               

                 



fig, ax = plt.subplots()

axis = ax.xaxis

axis.get_ticklocs()



    



axis.get_ticklabels()



    

                                                                               

                                                                        

                                  



axis.get_ticklines()



    

                                                                       

                                                    



axis.get_ticklabels(minor=True)

axis.get_ticklines(minor=True)



    

                                                                          

                                                         

                                                     

 

                                                                               

                                            

                                                                               

                                                                               

                                                                              

                                                                              

                                                                  

                                                                    

                                                                          

                                                              

                                                         

                                                                

                                                         

                                                           

                                                         

                                                                               

                                                                           

                                      

                                                                               

                                                                           

                                      

                                                                            

                                                                            

                                                                               

                                      

                                                                               

 

                                                                      

                               



                                                        

fig = plt.figure()

rect = fig.patch                        

rect.set_facecolor('lightgoldenrodyellow')



ax1 = fig.add_axes((0.1, 0.3, 0.4, 0.4))

rect = ax1.patch

rect.set_facecolor('lightslategray')





for label in ax1.xaxis.get_ticklabels():

                              

    label.set_color('red')

    label.set_rotation(45)

    label.set_fontsize(16)



for line in ax1.yaxis.get_ticklines():

                               

    line.set_color('green')

    line.set_markersize(25)

    line.set_markeredgewidth(3)



plt.show()



    

                     

 

                 

                 

 

                                                                        

                                                            

                                                                      

                                                                        

                                                                       

                                                                        

                  

 

                                                                            

                             

                                                                            

                                      

                                      

                                      

                                    

                                    

                                                                            

 

                                                                           

                                                                    

 

 

                                                

                                                                   

                                            

